### ISSUE TITLE
Linux R2M plugin froze after clicking on the Generate button while there is an error in the authorization header

### ISSUE THREAD

**Issue by pekboy** [magnetsystems/r2m-plugin-android#31]
Issue:
Plugin window froze when trying to generate asset with errors in the authorization header.

	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187268]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.table.JTableHeader.resizeAndRepaint(JTableHeader.java:660)
	at javax.swing.table.JTableHeader.columnAdded(JTableHeader.java:551)
	at javax.swing.table.DefaultTableColumnModel.fireColumnAdded(DefaultTableColumnModel.java:532)
	at javax.swing.table.DefaultTableColumnModel.addColumn(DefaultTableColumnModel.java:125)
	at org.jdesktop.swingx.table.DefaultTableColumnModelExt.addColumn(DefaultTableColumnModelExt.java:198)
	at org.jdesktop.swingx.JXTable.createAndAddColumns(JXTable.java:2601)
	at org.jdesktop.swingx.JXTable.createDefaultColumnsFromModel(JXTable.java:2575)
	at javax.swing.JTable.tableChanged(JTable.java:4386)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at javax.swing.JTable.setModel(JTable.java:3688)
	at org.jdesktop.swingx.JXTable.setModel(JXTable.java:1609)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.resetFields(PayloadPanel.java:189)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:143)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187270]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.JTable.resizeAndRepaint(JTable.java:5610)
	at javax.swing.JTable.columnAdded(JTable.java:4544)
	at org.jdesktop.swingx.JXTable.columnAdded(JXTable.java:2229)
	at javax.swing.table.DefaultTableColumnModel.fireColumnAdded(DefaultTableColumnModel.java:532)
	at javax.swing.table.DefaultTableColumnModel.addColumn(DefaultTableColumnModel.java:125)
	at org.jdesktop.swingx.table.DefaultTableColumnModelExt.addColumn(DefaultTableColumnModelExt.java:198)
	at org.jdesktop.swingx.JXTable.createAndAddColumns(JXTable.java:2601)
	at org.jdesktop.swingx.JXTable.createDefaultColumnsFromModel(JXTable.java:2575)
	at javax.swing.JTable.tableChanged(JTable.java:4386)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at javax.swing.JTable.setModel(JTable.java:3688)
	at org.jdesktop.swingx.JXTable.setModel(JXTable.java:1609)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.resetFields(PayloadPanel.java:189)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:143)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187270]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.table.JTableHeader.resizeAndRepaint(JTableHeader.java:660)
	at javax.swing.table.JTableHeader.columnAdded(JTableHeader.java:551)
	at javax.swing.table.DefaultTableColumnModel.fireColumnAdded(DefaultTableColumnModel.java:532)
	at javax.swing.table.DefaultTableColumnModel.addColumn(DefaultTableColumnModel.java:125)
	at org.jdesktop.swingx.table.DefaultTableColumnModelExt.addColumn(DefaultTableColumnModelExt.java:198)
	at org.jdesktop.swingx.JXTable.createAndAddColumns(JXTable.java:2601)
	at org.jdesktop.swingx.JXTable.createDefaultColumnsFromModel(JXTable.java:2575)
	at javax.swing.JTable.tableChanged(JTable.java:4386)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at javax.swing.JTable.setModel(JTable.java:3688)
	at org.jdesktop.swingx.JXTable.setModel(JXTable.java:1609)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.resetFields(PayloadPanel.java:189)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:143)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187273]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.JTable.resizeAndRepaint(JTable.java:5610)
	at javax.swing.JTable.columnAdded(JTable.java:4544)
	at org.jdesktop.swingx.JXTable.columnAdded(JXTable.java:2229)
	at javax.swing.table.DefaultTableColumnModel.fireColumnAdded(DefaultTableColumnModel.java:532)
	at javax.swing.table.DefaultTableColumnModel.addColumn(DefaultTableColumnModel.java:125)
	at org.jdesktop.swingx.table.DefaultTableColumnModelExt.addColumn(DefaultTableColumnModelExt.java:198)
	at org.jdesktop.swingx.JXTable.createAndAddColumns(JXTable.java:2601)
	at org.jdesktop.swingx.JXTable.createDefaultColumnsFromModel(JXTable.java:2575)
	at javax.swing.JTable.tableChanged(JTable.java:4386)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at javax.swing.JTable.setModel(JTable.java:3688)
	at org.jdesktop.swingx.JXTable.setModel(JXTable.java:1609)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.resetFields(PayloadPanel.java:189)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:143)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187284]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3340)
	at javax.swing.JComponent.hide(JComponent.java:5590)
	at java.awt.Component.show(Component.java:1657)
	at java.awt.Component.setVisible(Component.java:1607)
	at javax.swing.JComponent.setVisible(JComponent.java:2641)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.resetFields(PayloadPanel.java:191)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:143)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[10187293]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.JComponent.setForeground(JComponent.java:2703)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldTextColor(PayloadPanel.java:180)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:175)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.removeUpdate(PayloadPanel.java:203)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:260)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:623)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:591)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
MEvent. CASE!
Method{
methodName='userFollowTopics'
, testUrl='https://api.getsatisfaction.com/people/paul_6760472/followed'
, headers=[]
, paths=[PathPart{pathValue='people', variableName='', templatized=false}, PathPart{pathValue='paul_6760472', variableName='userId', templatized=true}, PathPart{pathValue='followed', variableName='', templatized=false}]
, queries=[]
, payload=''
, httpMethod=GET
, response=''
}
[10604078]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.JComponent.setForeground(JComponent.java:2703)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldTextColor(PayloadPanel.java:180)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.setFieldColor(PayloadPanel.java:175)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel$2.insertUpdate(PayloadPanel.java:197)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:202)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:749)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:708)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:670)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Method{
methodName='userFollowTopics'
, testUrl='https://api.getsatisfaction.com/people/paul_6760472/followed/topics.json'
, headers=[]
, paths=[PathPart{pathValue='people', variableName='', templatized=false}, PathPart{pathValue='paul_6760472', variableName='', templatized=false}, PathPart{pathValue='followed', variableName='', templatized=false}, PathPart{pathValue='topics.json', variableName='', templatized=false}]
, queries=[]
, payload=''
, httpMethod=GET
, response='The resource you requested does not exist'
}
Method{
methodName='gSPost'
, testUrl='https://api.getsatisfaction.com/topics.json'
, headers=[com.magnet.plugin.r2m.api.models.RequestHeaderModel@7342e217]
, paths=[PathPart{pathValue='topics.json', variableName='', templatized=false}]
, queries=[]
, payload='{
    "topic": 
        {
            "subject": "test for product regression", 
            "company_domain": "my_test_community", 
            "style": "praise", 
            "keywords": "keyword", 
            "additional_detail": "additional detail goes here",
            "products": ["community_thingamajig"],
            "emotitag":
                {
                    "face": "happy",
                    "feeling": "very happy",
                    "intensity": 2
                }
         }
}'
, httpMethod=POST
, response=''
}
[10916923]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
	at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:136)
	at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:126)
	at javax.swing.JComponent.repaint(JComponent.java:4805)
	at java.awt.Component.repaint(Component.java:3297)
	at javax.swing.text.WrappedPlainView.updateChildren(WrappedPlainView.java:292)
	at javax.swing.text.WrappedPlainView.insertUpdate(WrappedPlainView.java:463)
	at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1602)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1861)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:202)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:749)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:708)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:670)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
	at com.magnet.plugin.r2m.ui.tab.PayloadPanel.setPayload(PayloadPanel.java:236)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:249)
	at com.magnet.plugin.r2m.ui.tab.MethodTabPanel$4.onSuccess(MethodTabPanel.java:244)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.onSuccess(AbstractRequest.java:64)
	at com.magnet.plugin.r2m.api.requests.abs.BaseRequest.doWork(BaseRequest.java:77)
	at com.magnet.plugin.r2m.api.requests.abs.AbstractRequest.run(AbstractRequest.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Method{
methodName='gSPost'
, testUrl='https://api.getsatisfaction.com/topics.json'
, headers=[com.magnet.plugin.r2m.api.models.RequestHeaderModel@7342e217]
, paths=[PathPart{pathValue='topics.json', variableName='', templatized=false}]
, queries=[]
, payload='{
    "topic": 
        {
            "subject": "test for product regression", 
            "company_domain": "my_test_community", 
            "style": "praise", 
            "keywords": "keyword", 
            "additional_detail": "additional detail goes here",
            "products": ["community_thingamajig"],
            "emotitag":
                {
                    "face": "happy",
                    "feeling": "very happy",
                    "intensity": 2
                }
         }
}'
, httpMethod=POST
, response='{"status":"AccessDeniedError"}'
}

**Comment by pekboy** [comment]
This happened again but this time there was no error in the form and no authorization header.

**Comment by pekboy** [comment]
Sample API with header
https://app.asana.com/api/1.0/users
Key: Authorization
Value:  Basic MzQ1VUZ1VU8uTkFMV1NoeWVGY1JuYWNDUHN4c0FIblE6

Sample API
http://www.seismi.org/api/eqs/2013/02?min_magnitude=6

**Comment by etexier** [comment]
I disabled the "Test API" while the request is being processed. This way, user won't be able to click multiple times on the button. I think this is what was causing the issue. 
If there is a connection issue, the button will be disabled until the request times out (about 20 sec), and a error dialog will pop up.
